const commonActionTypes = {
    GET_ALL_WHATEVER: 'GET_ALL_WHATEVER',
    GET_ALL_WHATEVER_SUCCESS: 'GET_ALL_WHATEVER_SUCCESS',
    GET_ALL_WHATEVER_FAIL: 'GET_ALL_WHATEVER_FAIL',
    SET_FORM_INPUT:'SET_FORM_INPUT'
}

export default commonActionTypes;